#!/bin/bash

dims() {
	if [ $# -gt "1" ]
	then
		echo "Error" 1>&2
		exit 1
	elif [ $# = "1" ] && [ ! -r $2 ]
	then
		echo "Error" 1>&2
		exit 1
	else
		rows=$(wc -l $1)
		echo $rows | cut -f 1 -d " " # cut cuts the first field (-f 1) from a list of fields delimited by the string " " (-d)
		firstline=$(head -n 1 $1)
		# count=1
		# for i in $firstline
		# do
		# 	echo "stop 1"
		# 	if [ "$i" = "\t" ]
		# 	then
		# 		echo "stop 2"
		# 		$count=$(count+1)
		# 	fi
		# done
		# echo $count
		cols=$(echo $firstline | wc -w )
		echo $cols
		return 0
	fi		 		
}

transpose() {
	echo "tranpose"
}

mean() {
	echo "mean"
	sum=0
	for i in $2
	do
		echo $i
	done
}

add() {
	echo "add"
}

multipy() {
	echo "multiply"
}


datafilepath="datafile$$"
if [ "$#" = "0" ]
then 
	echo "Error, no arguments were passed" 1>&2
	exit 1
elif [ $1 = "add" ] || [ $1 = "multiply" ]
then
	if [ $# = "3" ]
	then
		$1 $2 $3
	else
		echo "Error" 1>&2
		exit 1
	fi
elif [ $1 = "dims" ] || [ $1 = "transpose" ] || [ $1 = "mean" ]
then
	if [ $# = "2" ]
	then
		$1 $2
	elif [ $# = "1" ]
	then
		cat > "$datafilepath"
		$1 "$datafilepath"
	else
		echo "Error" 1>&2
		exit 1
	fi
else
	echo "Error, function does not exist: $1" 1>&2
	exit 1
fi	
